name: Build and Package JavaFX App

on:
  push:
    branches:
      - main # or your default branch
  pull_request:
    branches:
      - main # or your default branch

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-13, macos-14]
        java: ['17.0.11+9'] # Specific, secure patch version of Java 17

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B clean package

      - name: Upload Windows Artifact
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: UIPTV-Windows
          path: target/dist/UIPTV-*.exe

      - name: Upload Linux Artifact
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: UIPTV-Linux
          path: target/dist/UIPTV-*.deb

      - name: Upload macOS Intel Artifact
        if: runner.os == 'macOS' && contains(matrix.os, '13')
        uses: actions/upload-artifact@v4
        with:
          name: UIPTV-macOS-Intel
          path: target/dist/UIPTV-*.dmg
          
      - name: Upload macOS Apple Silicon Artifact
        if: runner.os == 'macOS' && contains(matrix.os, '14')
        uses: actions/upload-artifact@v4
        with:
          name: UIPTV-macOS-Apple-Silicon
          path: target/dist/UIPTV-*.dmg
