name: Build, Package and Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            arch: x86_64
            profile: windows-x86_64
          - os: windows-latest-arm64
            arch: aarch64
            profile: windows-aarch64
          - os: macos-latest
            arch: x86_64
            profile: mac-x86_64
          - os: macos-latest
            arch: aarch64
            profile: mac-aarch64
          - os: ubuntu-latest
            arch: x86_64
            profile: linux-x86_64,pkg-deb
          - os: ubuntu-latest
            arch: x86_64
            profile: linux-x86_64,pkg-rpm
          - os: ubuntu-latest
            arch: x86_64
            profile: linux-x86_64,pkg-app-image
          - os: ubuntu-latest-arm64
            arch: aarch64
            profile: linux-aarch64,pkg-deb
          - os: ubuntu-latest-arm64
            arch: aarch64
            profile: linux-aarch64,pkg-rpm
          - os: ubuntu-latest-arm64
            arch: aarch64
            profile: linux-aarch64,pkg-app-image
        java: ['25']

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install RPM builder for DEB-based systems
        if: runner.os == 'Linux' && contains(matrix.profile, 'pkg-rpm')
        run: sudo apt-get update && sudo apt-get install -y rpm

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B clean package -P ${{ matrix.profile }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: UIPTV-${{ matrix.os }}-${{ matrix.arch }}
          path: |
            target/dist/*

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v7
        with:
          path: artifacts

      - name: Create Release and Upload Artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*/*
